### ISSUE TITLE
SS069 polygon is not compatible with pan and zoom

### ISSUE THREAD

**Issue by spydmobile** [intellifire/general_development_directions#54]
Created on behalf of Franco Nogarin(spydmobile)(spydmobile@gmail.com)
```
turf.min.js:1 Uncaught (in promise) Error: features must be of the same type
    at Tr (turf.min.js:1:87131)
    at turf.min.js:1:566425
    at Array.forEach (<anonymous>)
    at t.dissolve (turf.min.js:1:566200)
    at panAndZoomToFire (aFunctionLibrary.js:813:25)
```

**Comment by spydmobile** [comment]
updated turf.js and rewrote much geospatial logic.
